sexp = lparen operation | speech-acts rparen
<lparen> = <'('>
<rparen> = <')'>
operation = operator + args
operator = '+' | '-' | '*' | '/'
args = snumber+ ssexp*
<ssexp>   = space sexp
<snumber> = space number
<space>  = <#'[ ]*'>
number = #'[0-9]+'
speech-acts = performative + params
performative = 'out' | 'ask'
params = vector
