sexp = lparen operation rparen
<lparen> = <'('>
<rparen> = <')'>
operation = operator + args
operator = '+' | '-' | '*' | '/'
args = snumber+ ssexp*
<ssexp>   = space sexp
<snumber> = space number
<space>  = <#'[ ]*'>
number = #'[0-9]+'
